branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

osx_image: xcode10
language: swift

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - fastlane test
  
after_script:
  - fastlane coverage
  - ./cc-test-reporter format-coverage -t cobertura
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
