name: Build Example Project

on:
  workflow_dispatch:
  push:
    paths:
      - "Example/**"
      - "Sources/**"
  pull_request:
    paths:
      - "Example/**"
      - "Sources/**"

jobs:
  build:
    name: Build iOS example project
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcodebuild build -project Example/Example.xcodeproj -scheme Example-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14'
